### PR TITLE
Unchaining WIP-Release v0.1.43-alpha

### PR DESCRIPTION
**Pull request by SecUpwN**
Thanks to the wonderful work of @larsgrefer, we're now using a new and hopefully much better to manage [realm java database](https://github.com/realm/realm-java). Our current database design looks like this:

New Realm Database

**Other important details:** 

We display the Neighboring Cell information in two ways:  
1. through telephony manager methods which does not work on Samsung Devices
2. a fallback is available through the methods developed by Alexey
(Data is saved in an Array not in an table)

I strongly encourage all members of @CellularPrivacy/database to check out the latest changes and see if you can improve his work. @E3V3A, please don't be mad at me for merging this. Even though you did not respond in the pull request for this major change, I very much hope you will value the advantages of this new database - see https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/215#issuecomment-203433672: "We don't have to worry about OR-Mapping and get a nice java-api. And of course we can get rid of our 2000+ lines monster-class". Enjoy another fine release!

### CODE REVIEW

**Comment by SecUpwN** [comment]
Approved

**Comment by SecUpwN** [comment]
Approved

**Review by deeperdb — APPROVED** [review]
Ok

**Comment by Cokayakboy** [comment]
Cant open

**Pull request merged**
