### PR TITLE
Fix for crash when downloading OCID data in airplane mode

### PR DESCRIPTION
**Pull request by mimi89999**
>Thank you for submitting a pull request! Please add below details so that we can merge it faster.

---

- [X] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have reviewed and closely followed the [Style Guide](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki/Style-Guide) for this Android app.**

---

---

- [X] Bugfix (non-breaking change which fixes an existing issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (restructuring of existing code without changing its external functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

#831

---

### CODE REVIEW

**Comment by mimi89999** [comment]
@SecUpwN If no network data is available would it be good to get the info from the SIM?

**Comment by SecUpwN** [comment]
>If no network data/info is available would it be good to get the info from the SIM?

@mimi89999 thanks for crafting this fix! I am afraid I don't get which data you mean to get from the SIM.

**Comment by mimi89999** [comment]
Yes, I mean the ***Network Operator***

**Comment by SecUpwN** [comment]
>Yes, I mean the ***Network Operator***

If we're not reading it from the SIM, please implement that. It might solve the already closed #749 as well.

**Comment by mimi89999** [comment]
AFAIK we are showing it on the info screen.
I'm thinking of passing it to downloadBtsData... if we can't get it from the network...

**Comment by SecUpwN** [comment]
>I'm thinking of passing it to downloadBtsData... if we can't get it from the network...

Do you want to remove it from the info screen and add it to the download? Not sure what you mean..

**Comment by mimi89999** [comment]
No...

**Comment by mimi89999** [comment]
Look at `downloadBtsDataIfApiKeyAvailable`...

**Comment by mimi89999** [comment]
Now think about what happens when a device is in airplane mode and a user clicks on ***download OpenCellId data*** (aftet my fix).

**Comment by SecUpwN** [comment]
Oh, I get it. I'd prefer a separate pull request if this this is not directly related to fixing #831.
But if you feel that these changes will improve stability when fetching the key, add it here.

**Comment by mimi89999** [comment]
I will create another PR...

**Comment by SecUpwN** [comment]
Approved!

**Comment by mimi89999** [comment]
@SecUpwN When do you plan to make a new release of AIMSICD?

**Comment by SecUpwN** [comment]
>When do you plan to make a new release of AIMSICD?

Later tonight, German time. But definately before monday.
I'll pull in any mergeable pull requests before doing so.

**Pull request merged**
