### PR TITLE
Restructure the main activity to use the material TabLayout

### PR DESCRIPTION
**Pull request by larsgrefer**
Don't merge

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks, what improves this, @larsgrefer? Please add a screenshot and a short sentence to the OP.

**Comment by larsgrefer** [comment]
I will split some of the things I've done here to different PR to better show what happens

**Comment by SecUpwN** [comment]
>I will split some of the things I've done here to different PR to better show what happens

@agilob, please be so kind and have a look at these things **before** we mmerge them. Thanks!

**Comment by larsgrefer** [comment]
@SecUpwN In fact the first of those PRs is already merged: #743

**Comment by SecUpwN** [comment]
And I am thankful for your extremely hard work, @larsgrefer. Are you currently working on UI/UX? I am still worried that #258 has so many proposals on what to do or not to do. I just want our app to look and feel unique while at the same time being as easy to use as possible and be expandable for features.

**Comment by SecUpwN** [comment]
@He3556, would you please have a look at this pull request and tell us if you approve it? Thanks!

**Comment by larsgrefer** [comment]
This PR is not finished yet

**Comment by SecUpwN** [comment]
>This PR is not finished yet

What is missing here? Seems as if thisPR now has a merge conflict as well.

**Comment by larsgrefer** [comment]
@SecUpwN The actionBar/Toolbar is broken in some activities

**Comment by SecUpwN** [comment]
>The actionBar/Toolbar is broken in some activities

Ok, take your time. Sorry for nagging, @larsgrefer.

**Comment by SecUpwN** [comment]
>The actionBar/Toolbar is broken in some activities

@larsgrefer, please do a rebase here as well so that @tt3mm can assist finishing this pull request. Thanks!

**Comment by SecUpwN** [comment]
@f3ndot, are you able to update this pull request and see what needs to be done for finishing it?

**Comment by SecUpwN** [comment]
@CellularPrivacy/design would you please see if you can finish this pull request?

**Pull request closed without merging**
