### PR TITLE
Set targetSdk to 22 and use a white notification icon

### PR DESCRIPTION
**Pull request by larsgrefer**
see #512 

not ready to merge yet

comments are welcome

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks for proposing this, @larsgrefer. Please add a preview of the Icon. Did you change any designs?

**Comment by larsgrefer** [comment]
screenshot_20160316-224606
screenshot_20160316-224644

**Comment by SecUpwN** [comment]
Wonderful, @larsgrefer! Will this new white notification Icon change its background color (e. g. medium -> yellow, high -> orange and danger -> red) when the status changes as well?

**Comment by larsgrefer** [comment]
The icon in the statusbar is always white (first picture).

The full notification shows the white icon on a colored background, where the color indicates the current status

**Comment by SecUpwN** [comment]
>The icon in the statusbar is always white (first picture).

Oh, now I see. I guess we can't prevent that Android will keep this way of displaying notification Icons and I will have to detach my mind from wanting the notification Icon to stay colored. As long as users are able to see the current state of our app when looking at the locked screen, I guess all is good.

>The full notification shows the white icon on a colored background, where the color indicates the current status

But both colors (of the large and the small Icon) are changing correctly?

**Comment by larsgrefer** [comment]
>But both colors (of the large and the small Icon) are changing correctly?

Yes

**Comment by SecUpwN** [comment]
>Yes

Approved!

**Comment by larsgrefer** [comment]
@SecUpwN A second option is only using the small icon:
screenshot_20160320-214706

**Comment by SecUpwN** [comment]
>A second option is only using the small icon

Looks good too, but it seems as if our designed Status Icons are not used anymore then. I prefer to keep it they way it will be with the current changes of the pull request until there is immediate need to change it.

**Pull request merged**
