### PR TITLE
Fixed empty neighbor cells list detection

### PR DESCRIPTION
**Pull request by pchk**
#264

### CODE REVIEW

**Comment by agilob** [comment]
This is a risky change that will rise a lot of false-positives. LTE cells don't provide any neighbouring cells. My LG that I have also doesn't has such functionality of any kind of cells, it's just not supported by manufacturer on the device. Rising alarm because of such reason will be misleading and people will come here to ask if they are targeted.

**Comment by pchk** [comment]
Alert will never be shown if your phone does not support that. 
Only when your phone was been able to detect some neighbor cells in the past, but after connection to new cell it does not provide any neighbors.
As for LTE cells. If so, check for connection type will be enough.

**Comment by pchk** [comment]
Check this. A think that is exactly what we need.

**Comment by SecUpwN** [comment]
Thanks for proposing this fix! @larsgrefer or @CellularPrivacy/celltower would you please check this pull request gor further improvements?

**Comment by SecUpwN** [comment]
Approved! Thanks for this fix, @pchk! @Nordlenning, have a look after I merged this. We need some extensive testing, it would be lovely if you could assist and report back in #264. @He3556 since you actually opened #264, please be so kind and test the now bleeding edge APK from `Buildozer` as well!

[Approved with PullApprove](https://pullapprove.com/CellularPrivacy/Android-IMSI-Catcher-Detector/pull-request/874/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=CellularPrivacy/Android-IMSI-Catcher-Detector)

**Pull request merged**
